WORLD_NAME:                           "reInvent2019_wide"
CHANGE_START_POSITION:                "false"
ALTERNATE_DRIVING_DIRECTION:          "false"
NUMBER_OF_OBSTACLES:                  "0"
IS_OBSTACLE_BOT_CAR:                  "false"
RANDOMIZE_OBSTACLE_LOCATIONS:         "false"
# OBJECT_POSITIONS:
#     - 0.1690708037909166, -1
#     - 0.2638102569075569, 1
#     - 0.4072827740044651, -1
#     - 0.5804718430735435, 1
#     - 0.6937442410812812, -1
#     - 0.7864867324330095, 1
IS_LANE_CHANGE:                       "false"
LOWER_LANE_CHANGE_TIME:               "3.0"
UPPER_LANE_CHANGE_TIME:               "5.0"
LANE_CHANGE_DISTANCE:                 "1.0"
NUMBER_OF_BOT_CARS:                   "0"
MIN_DISTANCE_BETWEEN_BOT_CARS:        "2.0"
RANDOMIZE_BOT_CAR_LOCATIONS:          "false"
BOT_CAR_SPEED:                        "0.2"
ENABLE_DOMAIN_RANDOMIZATION:          "false"